services:
  - type: web
    name: weed-detection
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    runtime: python3
    pythonVersion: "3.10.12"

