services:
  - type: web
    name: weed-detection
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    runtime: python3
    pythonVersion: "3.10.12"
    startCommand: "gunicorn app:app -c gunicorn.conf.py"



